name: CI

on:
  push:
    paths:
    - '**.rs'
  pull_request:
  workflow_dispatch:
    inputs:
      test:
        description: 'Testing the build workflow'
        required: true
        default: 'true'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.45.0
          override: true

      # Ensure all code has been formatted with rustfmt
      - run: rustup component add rustfmt
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check --color always

      - run: rustup component add clippy
      - name: Clippy check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build target ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, linux-static, armv7, armv7-static, arm64, arm64-static, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest

          - name: linux-static
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cargo_config: |
              [target.x86_64-unknown-linux-musl]
            build_flags: --target x86_64-unknown-linux-musl

          - name: armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build_deps: >
              gcc-arm-linux-gnueabihf
            cargo_config: |
              [target.armv7-unknown-linux-gnueabihf]
              linker = "arm-linux-gnueabihf-gcc"
            build_flags: --target armv7-unknown-linux-gnueabihf

          - name: armv7-static
            os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            build_deps: >
              gcc-arm-linux-gnueabihf
            cargo_config: |
              [target.armv7-unknown-linux-musleabihf]
              linker = "arm-linux-gnueabihf-gcc"
            build_flags: --target armv7-unknown-linux-musleabihf

          - name: arm64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build_deps: >
              gcc-aarch64-linux-gnu
            cargo_config: |
              [target.aarch64-unknown-linux-gnu]
              linker = "aarch64-linux-gnu-gcc"
            build_flags: --target aarch64-unknown-linux-gnu

          - name: arm64-static
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            build_deps: >
              gcc-aarch64-linux-gnu
            cargo_config: |
              [target.aarch64-unknown-linux-musl]
              linker = "aarch64-linux-gnu-gcc"
              rustflags = [ "-C", "target-feature=+crt-static", "-C", "link-arg=-lgcc" ]
            build_flags: --target aarch64-unknown-linux-musl

          - name: windows
            os: windows-latest

          - name: macos
            os: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.45.0
          override: true
      
      - name: Add target
        run: rustup target add ${{ matrix.target }}
        if: matrix.target != ''

      - name: Install linux build dependencies
        run: sudo apt install ${{ matrix.build_deps }}
        if: matrix.build_deps != ''

      - name: Set up .cargo/config
        run: |
          mkdir .cargo
          echo '${{ matrix.cargo_config }}' > .cargo/config
        if: matrix.cargo_config != ''

      - name: Build for target
        run: cargo build --verbose --no-default-features ${{ matrix.build_flags }}